name: CI/CD pipeline

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
steps:
  - run: echo "Comienza despliegue"
  - run: echo "El usuario {{ github.actor }} esta desplegando la aplicación"
  - name: Checkout repository
    uses: actions/checkout@v2
  - name: Setup Node.js
    uses: actions/setup-node@v1
    run: echo "Ejecuta comandos"
  - name: Install dependencies
    run: npm install
  - name: Run tests
    run: npm test
